#!/bin/bash
# Setup cron jobs for Lambda infrastructure monitoring and backup

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PYTHON=$(which python3)

# Markers for managed section
MARKER_START="# BEGIN HERON-INFRA MANAGED BLOCK"
MARKER_END="# END HERON-INFRA MANAGED BLOCK"

# Create logs directory
mkdir -p "$SCRIPT_DIR/logs"

echo "Setting up cron jobs for heron-infra..."
echo "Project directory: $SCRIPT_DIR"
echo "Python: $PYTHON"
echo ""

# Check if config.env exists
if [ ! -f "$SCRIPT_DIR/config.env" ]; then
    echo "WARNING: config.env not found!"
    echo "Please copy config.env.example to config.env and add your Lambda API key:"
    echo "  cp $SCRIPT_DIR/config.env.example $SCRIPT_DIR/config.env"
    echo ""
fi

# Check SSH keys directory
SSH_KEYS_DIR=$(grep "^SSH_KEYS_DIR=" "$SCRIPT_DIR/config.env" 2>/dev/null | cut -d= -f2 | sed 's/~/$HOME/g')
if [ -n "$SSH_KEYS_DIR" ]; then
    eval SSH_KEYS_DIR="$SSH_KEYS_DIR"
    if [ ! -d "$SSH_KEYS_DIR" ]; then
        echo "NOTE: SSH keys directory does not exist: $SSH_KEYS_DIR"
        echo "Create it and add your Lambda SSH keys (named after the key names in Lambda):"
        echo "  mkdir -p $SSH_KEYS_DIR"
        echo "  cp your-key.pem $SSH_KEYS_DIR/your-lambda-key-name"
        echo ""
    fi
fi

# Get current crontab (or empty if none)
CURRENT_CRON=$(crontab -l 2>/dev/null || echo "")

# Remove existing managed block (everything between markers, inclusive)
if echo "$CURRENT_CRON" | grep -q "$MARKER_START"; then
    # Use sed to remove the managed block
    CLEANED_CRON=$(echo "$CURRENT_CRON" | sed "/$MARKER_START/,/$MARKER_END/d")
else
    CLEANED_CRON="$CURRENT_CRON"
fi

# Remove any trailing blank lines from cleaned cron
CLEANED_CRON=$(echo "$CLEANED_CRON" | sed -e :a -e '/^\n*$/{$d;N;ba' -e '}')

# Build the managed block
MANAGED_BLOCK="$MARKER_START
# Auto-generated by heron-infra/setup_cron.sh
# Do not edit this block manually - changes will be overwritten
#
# Monitor: collect GPU stats, update SSH config, track costs
* * * * * cd $SCRIPT_DIR/scripts && $PYTHON monitor.py >> $SCRIPT_DIR/logs/monitor.log 2>&1
#
# Terminate: shut down instances idle for too long
*/5 * * * * cd $SCRIPT_DIR/scripts && $PYTHON terminate_idle_instances.py >> $SCRIPT_DIR/logs/terminate.log 2>&1
#
# Backup: rsync instance home directories
*/30 * * * * cd $SCRIPT_DIR/scripts && $PYTHON backup.py >> $SCRIPT_DIR/logs/backup.log 2>&1
$MARKER_END"

# Combine: existing cron + blank line + managed block
if [ -n "$CLEANED_CRON" ]; then
    NEW_CRON="$CLEANED_CRON

$MANAGED_BLOCK"
else
    NEW_CRON="$MANAGED_BLOCK"
fi

# Install new crontab
echo "$NEW_CRON" | crontab -

echo "Cron jobs installed successfully!"
echo ""
echo "Scheduled jobs:"
echo "  - Monitor:   every minute      (GPU stats, SSH config, costs)"
echo "  - Terminate: every 5 minutes   (idle instance shutdown)"
echo "  - Backup:    every 30 minutes  (rsync home directories)"
echo ""
echo "Logs:"
echo "  - $SCRIPT_DIR/logs/monitor.log"
echo "  - $SCRIPT_DIR/logs/terminate.log"
echo "  - $SCRIPT_DIR/logs/backup.log"
echo ""
echo "Commands:"
echo "  View cron:    crontab -l"
echo "  Remove block: crontab -l | sed '/$MARKER_START/,/$MARKER_END/d' | crontab -"
